apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: helm
spec:
  version: "v0.0.2"
  homepage: https://github.com/sandipchitale/kubectl-helm-get-templates
  shortDescription: "Kubectl plugin to run helm commands including custom commands"
  description: |
    Kubectl plugin to run helm commands including
    custom commands like
    get templates RELEASENAME [--revision N].
  platforms:
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/sandipchitale/kubectl-helm-get-templates/archive/v0.0.1.zip
    # 'sha256' is the sha256sum of the url (archive file) above
    sha256:
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "dist/win/kubectl-helm_get_templates.exe"
      to: "."
    - from: "LICENSE"
      to: "."
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: kubectl-helm_get_templates.exe
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/sandipchitale/kubectl-helm-get-templates/archive/v0.0.1.zip
    # 'sha256' is the sha256sum of the url (archive file) above
    sha256:
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "dist/linux/kubectl-helm_get_templates"
      to: "."
    - from: "LICENSE"
      to: "."
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: kubectl-helm_get_templates
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/sandipchitale/kubectl-helm-get-templates/archive/v0.0.1.zip
    # 'sha256' is the sha256sum of the url (archive file) above
    sha256:
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "dist/darwin/kubectl-helm_get_templates"
      to: "."
    - from: "LICENSE"
      to: "."
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: kubectl-helm_get_templates